mysql:
 image: mysql:1
 command: sh -c "sleep 10 && node /opt/backend/index.js"
 networks:
 - expense
 volumes:
 - nginx_vol:/var/lib/mysql
 container_name: mysql
 


backend:
 image: frontend:1
 networks:
 - expense
 container_name: backend
 depends_on:
 - mysql


frontend:
 image: frontend:1
 networks:
 - expense
 ports:
 - 80:80
 depends_on:
 - backend
 container_name: frontend
 

